// Qualification of the implementation against the reference data, WITH a coverage report.
//
// The harness holds NO expected value of its own: it replays reference-data.csv, which is
// section 10 of the specification. That is what makes it a qualification rather than a
// test written by whoever wrote the code — a test whose expected values come out of the
// implementation verifies nothing.
//
// It also reads the specification itself, to answer the question a green suite never
// answers on its own: does what we ran actually cover what the specification requires?
//
//     javac -encoding UTF-8 -d /tmp/mb $(find src -name '*.java')
//     java -cp /tmp/mb method.massbalance.MassBalanceTest \
//          code/src/test/resources/reference-data.csv \
//          spec/SPEC-MAS-001.en.md reports/TEST-REPORT.md
//
// Exit code: 1 if a case deviates or a required item is uncovered, 0 otherwise.

package method.massbalance;

import method.spec.ImplementsSpec;

import java.io.IOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.regex.*;

public final class MassBalanceTest {

    /** The identities appendix, in the language of the document we read: English. */
    static final String ANNEXE_TITRE = "## Appendix — Identities";

    /** Start of a table row, with the explicit anchor the specification carries. */
    static final String ANCRE = "^\\|\\s*(?:<a id=\"[^\"]+\"></a>)?\\s*";

    static final List<String> lines = new ArrayList<>();
    static final Set<String> exercised = new TreeSet<>();
    static int deviations = 0;

    record Expected(String componentId, BigDecimal fraction, String expectedMass) {}

    public static void main(String[] args) throws IOException {
        System.setOut(new java.io.PrintStream(new java.io.FileOutputStream(
                java.io.FileDescriptor.out), true, StandardCharsets.UTF_8));

        Path data = Paths.get(args.length > 0 ? args[0] : "reference-data.csv");
        Path spec = Paths.get(args.length > 1 ? args[1] : "spec/SPEC-MAS-001.en.md");

        say("# Test report — SPEC-MAS-001");
        say("");
        say("*Generated by `MassBalanceTest`. Expected values come from the specification,");
        say("never from the implementation.*");
        say("");
        say("## Reference cases");
        say("");
        say("| Case | Result | Detail |");
        say("|---|---|---|");

        for (String line : Files.readAllLines(data, StandardCharsets.UTF_8))
            if (!line.isBlank() && !line.startsWith("#")) replay(line);

        say("");
        permutationInvariance();
        coverageReport(spec);

        say("");
        say(deviations == 0
                ? "**All reference cases pass, and every required item is covered.**"
                : "**" + deviations + " item(s) in deviation — see `DEVIATIONS.md` for what to do.**");

        Path report = Paths.get(args.length > 2 ? args[2] : "reports/TEST-REPORT.md");
        Files.createDirectories(report.toAbsolutePath().getParent());
        Files.write(report, (String.join("\n", lines) + "\n").getBytes(StandardCharsets.UTF_8));
        lines.forEach(System.out::println);
        System.exit(deviations > 0 ? 1 : 0);
    }

    /** Replays one reference case and compares it with the expected values. */
    @ImplementsSpec({"RG-010", "RG-020", "RG-030", "RG-040", "RG-050",
                     "E-MAS-001", "E-MAS-002", "E-MAS-003", "E-MAS-004"})
    static void replay(String line) {
        String[] f = line.split(";", -1);
        String id = f[0];
        BigDecimal targetMass = new BigDecimal(f[1]);
        BigDecimal step = new BigDecimal(f[2]);
        String expectedError = f[3].trim();

        List<Expected> expected = new ArrayList<>();
        List<MassBalance.Component> components = new ArrayList<>();
        for (String c : f[4].split("\\|")) {
            String[] p = c.split(":", -1);
            expected.add(new Expected(p[0], new BigDecimal(p[1]), p[2]));
            components.add(new MassBalance.Component(p[0], new BigDecimal(p[1])));
        }

        MassBalance.Request request = new MassBalance.Request(targetMass, step, components);

        if (!expectedError.isEmpty()) {
            try {
                MassBalance.compute(request);
                fail(id, "no error raised, " + expectedError + " expected");
            } catch (MassBalance.BusinessError e) {
                if (e.code.equals(expectedError)) {
                    exercised.add(expectedError);
                    // A rejection on the residual is, by construction, a case that
                    // arbitrates the value of the bound.
                    if (expectedError.equals("E-MAS-002")) exercised.add("P-02");
                    pass(id, "rejected as expected — `" + expectedError + "`");
                } else {
                    fail(id, "raised " + e.code + ", expected " + expectedError);
                }
            }
            return;
        }

        MassBalance.Result r;
        try {
            r = MassBalance.compute(request);
        } catch (MassBalance.BusinessError e) {
            fail(id, "unexpected rejection: " + e.getMessage());
            return;
        }

        boolean ok = true;
        for (int i = 0; i < expected.size(); i++) {
            BigDecimal want = new BigDecimal(expected.get(i).expectedMass());
            BigDecimal got = r.dispensed().get(i).dispensedMass();
            if (got.compareTo(want) != 0) {
                fail(id, expected.get(i).componentId()
                        + ": expected " + want + " kg, got " + got + " kg");
                ok = false;
            }
        }
        if (ok) exercised.addAll(List.of("RG-010", "RG-020", "RG-030", "RG-040", "RG-050"));

        if (!invariant01(r, targetMass)) { ok = false; }
        if (!invariant02(r, step))       { ok = false; }
        if (!invariant03(r))             { ok = false; }
        if (ok) exercised.addAll(List.of("INV-01", "INV-02", "INV-03"));

        String note = "";
        // P-02 is arbitrated by a case sitting exactly ON the bound: one step less and it
        // would be rejected. Anything comfortably inside the bound decides nothing.
        if (steps(r.residual(), step).replace("-", "")
                .equals(String.valueOf(MassBalance.P_02_MAX_RESIDUAL_STEPS))) {
            exercised.add("P-02");
            note += " · **decides `P-02`** — the residual sits exactly on the bound";
        }
        if (decidesP01(targetMass, step, components)) {
            exercised.add("P-01");
            note = " · **decides `P-01`** — a nominal mass falls on a half-step, "
                 + "where HALF_EVEN and HALF_UP part company";
        }
        if (ok) pass(id, r.dispensed().size() + " doses · residual " + r.residual()
                + " kg (" + steps(r.residual(), step) + " step(s)) · INV-01 to INV-03 hold"
                + note);
    }

    /**
     * Does this case arbitrate P-01? Only if some nominal mass falls exactly halfway
     * between two balance steps — that is the one place where HALF_EVEN and HALF_UP
     * disagree. Everywhere else the parameter could be anything and the sheet would be
     * identical, which is what the reference set looked like before CT-10.
     */
    @ImplementsSpec("P-01")
    static boolean decidesP01(BigDecimal targetMass, BigDecimal step,
                              List<MassBalance.Component> components) {
        for (MassBalance.Component c : components) {
            BigDecimal inSteps = targetMass.multiply(c.targetMassFraction())
                    .divide(step, 6, java.math.RoundingMode.HALF_EVEN);
            BigDecimal fraction = inSteps.subtract(
                    inSteps.setScale(0, java.math.RoundingMode.FLOOR));
            if (fraction.compareTo(new BigDecimal("0.5")) == 0) return true;
        }
        return false;
    }

    /** INV-01 — mass conservation, at strict equality. */
    @ImplementsSpec("INV-01")
    static boolean invariant01(MassBalance.Result r, BigDecimal targetMass) {
        BigDecimal sum = r.dispensed().stream()
                .map(MassBalance.Dispensed::dispensedMass)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        if (sum.compareTo(targetMass) == 0) return true;
        say("| | **DEVIATION** | INV-01: sum " + sum + " ≠ target mass " + targetMass + " |");
        deviations++;
        return false;
    }

    /** INV-02 — every dose is an integer multiple of the balance step. */
    @ImplementsSpec("INV-02")
    static boolean invariant02(MassBalance.Result r, BigDecimal step) {
        for (MassBalance.Dispensed d : r.dispensed())
            if (d.dispensedMass().remainder(step).compareTo(BigDecimal.ZERO) != 0) {
                say("| | **DEVIATION** | INV-02: " + d.componentId() + " = "
                        + d.dispensedMass() + " is not a multiple of " + step + " |");
                deviations++;
                return false;
            }
        return true;
    }

    /** INV-03 — no dose is negative. A negative residual must not eat a dose. */
    @ImplementsSpec("INV-03")
    static boolean invariant03(MassBalance.Result r) {
        for (MassBalance.Dispensed d : r.dispensed())
            if (d.dispensedMass().compareTo(BigDecimal.ZERO) < 0) {
                say("| | **DEVIATION** | INV-03: " + d.componentId()
                        + " = " + d.dispensedMass() + " is negative |");
                deviations++;
                return false;
            }
        return true;
    }

    /**
     * INV-04 — invariance under permutation, on GENERATED inputs.
     *
     * This is the check that catches an implementation which "forgot" the tie-break of
     * RG-050: it passes every nominal case and gets it wrong the day the components are
     * entered in a different order. No list of cases replaces a property tested on
     * generated inputs.
     */
    @ImplementsSpec("INV-04")
    static void permutationInvariance() {
        List<MassBalance.Component> base = List.of(
                new MassBalance.Component("CMP-A", new BigDecimal("0.400000")),
                new MassBalance.Component("CMP-B", new BigDecimal("0.400000")),
                new MassBalance.Component("CMP-C", new BigDecimal("0.200000")));
        MassBalance.Request reference = new MassBalance.Request(
                new BigDecimal("1.001"), new BigDecimal("0.001"), base);
        MassBalance.Result want = MassBalance.compute(reference);

        Random rng = new Random(20260821L);   // fixed seed: the property is replayable
        int permutations = 200;
        for (int i = 0; i < permutations; i++) {
            List<MassBalance.Component> shuffled = new ArrayList<>(base);
            Collections.shuffle(shuffled, rng);
            MassBalance.Result got = MassBalance.compute(new MassBalance.Request(
                    reference.targetBatchMass(), reference.balanceStep(), shuffled));

            for (MassBalance.Dispensed a : want.dispensed()) {
                BigDecimal m = got.dispensed().stream()
                        .filter(d -> d.componentId().equals(a.componentId()))
                        .findFirst().orElseThrow().dispensedMass();
                if (m.compareTo(a.dispensedMass()) != 0) {
                    say("");
                    say("**INV-04 violated** on permutation " + shuffled.stream()
                            .map(MassBalance.Component::componentId).toList()
                            + ": " + a.componentId() + " is " + m
                            + " instead of " + a.dispensedMass());
                    deviations++;
                    return;
                }
            }
        }
        say("## Property tested on generated inputs");
        say("");
        say("| Property | Inputs | Result |");
        say("|---|---|---|");
        say("| `INV-04` — the result is invariant under permutation of the components | "
                + permutations + " permutations | OK |");
        exercised.add("INV-04");
    }

    /**
     * Reads the specification and reports what the run did NOT cover. A green suite
     * proves nothing about the cases nobody wrote.
     */
    static void coverageReport(Path spec) throws IOException {
        String text = Files.readString(spec);
        // The identities annexe cites every object: reading it would take a UUID for
        // the statement of an invariant. We stop at the body of the document.
        int annexe = text.indexOf(ANNEXE_TITRE);
        if (annexe >= 0) text = text.substring(0, annexe);

        Map<String, String> required = new LinkedHashMap<>();
        collect(required, text, "^###\\s+(RG-\\d+)\\s+—\\s+(.+)$");
        collect(required, text, ANCRE + "`(INV-\\d+)`\\s*\\|\\s*([^|]+)");
        collect(required, text, ANCRE + "`(E-[A-Z]+-\\d+)`\\s*\\|\\s*([^|]+)");
        Map<String, String> parametres = new LinkedHashMap<>();
        collect(parametres, text, ANCRE + "`(P-\\d+)`\\s*\\|\\s*([^|]+)");

        say("");
        say("## Coverage of what the specification requires");
        say("");
        say("| Item | Statement | Covered |");
        say("|---|---|---|");
        int uncovered = 0;
        for (var e : required.entrySet()) {
            boolean ok = exercised.contains(e.getKey());
            if (!ok) uncovered++;
            say("| `" + e.getKey() + "` | " + truncate(e.getValue(), 58) + " | "
                    + (ok ? "yes" : "**NO**") + " |");
        }
        if (uncovered > 0) {
            deviations += uncovered;
            say("");
            say("**" + uncovered + " item(s) of the specification are exercised by no test.**");
        }

        // A parameter that appears in the code is not a parameter under test. It is under
        // test only if some case would publish different masses were it changed.
        say("");
        say("## Parameters, and whether any case decides them");
        say("");
        say("| Parameter | Statement | Decided by a case |");
        say("|---|---|---|");
        for (var e : parametres.entrySet())
            say("| `" + e.getKey() + "` | " + truncate(e.getValue(), 48) + " | "
                    + (exercised.contains(e.getKey())
                       ? "yes" : "**no — its value is never arbitrated**") + " |");
    }

    static void collect(Map<String, String> into, String text, String regex) {
        Matcher m = Pattern.compile(regex, Pattern.MULTILINE).matcher(text);
        while (m.find()) into.putIfAbsent(m.group(1), m.group(2).trim());
    }

    /** The residual expressed in balance steps — the unit P-02 is written in. */
    static String steps(BigDecimal residual, BigDecimal step) {
        return residual.divide(step, 0, java.math.RoundingMode.HALF_EVEN).toPlainString();
    }

    static String truncate(String s, int n) {
        s = s.replaceAll("\\s+", " ").replace("|", "/").trim();
        return s.length() > n ? s.substring(0, n) + "…" : s;
    }

    static void say(String s) { lines.add(s); }

    static void pass(String id, String detail) {
        say("| `" + id + "` | OK | " + detail + " |");
    }

    static void fail(String id, String detail) {
        say("| `" + id + "` | **DEVIATION** | " + detail + " |");
        deviations++;
    }
}
