// Qualification of the implementation against the reference data, WITH a coverage report.
//
// The harness holds NO expected value of its own: it replays reference-data.csv, which is
// section 10 of the specification. And it reads the specification itself, to answer two
// questions a green suite never answers on its own:
//
//     does what we ran cover what the specification requires?
//     and does any case actually DECIDE each parameter?
//
// The second one is answered by re-running each case with one parameter changed. A
// parameter whose perturbation changes nothing, anywhere, is approved, dated, implemented
// — and verified by nothing.
//
//     javac -encoding UTF-8 -d /tmp/wth $(find src -name '*.java')
//     java -cp /tmp/wth method.weathersummary.WeatherSummaryTest \
//          code/src/test/resources/reference-data.csv \
//          spec/SPEC-WTH-001.en.md reports/TEST-REPORT.md
//
// Exit code: 1 if a case deviates or a required item is uncovered, 0 otherwise.

package method.weathersummary;

import method.spec.ImplementsSpec;
import method.weathersummary.WeatherSummary.*;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.regex.*;

public final class WeatherSummaryTest {

    /** The identities appendix, in the language of the document we read: English. */
    static final String ANNEXE_TITRE = "## Appendix — Identities";

    /** Start of a table row, with the explicit anchor the specification carries. */
    static final String ANCRE = "^\\|\\s*(?:<a id=\"[^\"]+\"></a>)?\\s*";

    static final DateTimeFormatter HHMM = DateTimeFormatter.ofPattern("HH:mm");

    static final List<String> lines = new ArrayList<>();
    static final Set<String> exercised = new TreeSet<>();
    static final Map<String, List<String>> decidedBy = new LinkedHashMap<>();
    static int deviations = 0;

    /** One reference case, as the specification states it. */
    record Case(String id, Request request, String expectedError, String expected) {}

    /** A parameter, and the perturbation used to find out whether a case decides it. */
    record Perturbation(String id, String description, Parameters value) {}

    static final List<Perturbation> PERTURBATIONS = List.of(
        new Perturbation("P-01", "rejection factor 2.0 → 2.5",
            new Parameters(2.5, 5, 6, RoundingMode.HALF_EVEN, 1, 0.0)),
        new Perturbation("P-02", "maximum rounds 5 → 10",
            new Parameters(2.0, 10, 6, RoundingMode.HALF_EVEN, 1, 0.0)),
        new Perturbation("P-03", "minimum readings 6 → 2",
            new Parameters(2.0, 5, 2, RoundingMode.HALF_EVEN, 1, 0.0)),
        new Perturbation("P-04", "rounding mode HALF_EVEN → HALF_UP",
            new Parameters(2.0, 5, 6, RoundingMode.HALF_UP, 1, 0.0)),
        new Perturbation("P-05", "published decimals 1 → 2",
            new Parameters(2.0, 5, 6, RoundingMode.HALF_EVEN, 2, 0.0)),
        new Perturbation("P-06", "frost threshold 0.0 → 0.5 °C",
            new Parameters(2.0, 5, 6, RoundingMode.HALF_EVEN, 1, 0.5)));

    public static void main(String[] args) throws IOException {
        System.setOut(new java.io.PrintStream(new java.io.FileOutputStream(
                java.io.FileDescriptor.out), true, StandardCharsets.UTF_8));

        Path data = Paths.get(args.length > 0 ? args[0] : "reference-data.csv");
        Path spec = Paths.get(args.length > 1 ? args[1] : "spec/SPEC-WTH-001.en.md");

        List<Case> cases = new ArrayList<>();
        for (String line : Files.readAllLines(data, StandardCharsets.UTF_8))
            if (!line.isBlank() && !line.startsWith("#")) cases.add(parse(line));

        say("# Test report — SPEC-WTH-001");
        say("");
        say("*Generated by `WeatherSummaryTest`. Expected values come from the specification,");
        say("never from the implementation.*");
        say("");
        say("## Reference cases");
        say("");
        say("| Case | Result | Detail |");
        say("|---|---|---|");
        for (Case c : cases) replay(c);

        say("");
        permutationInvariance(cases);
        parameterArbitration(cases);
        coverageReport(spec);

        say("");
        say(deviations == 0
                ? "**All reference cases pass, and every required item is covered.**"
                : "**" + deviations + " item(s) in deviation.**");

        Path report = Paths.get(args.length > 2 ? args[2] : "reports/TEST-REPORT.md");
        Files.createDirectories(report.toAbsolutePath().getParent());
        Files.write(report, (String.join("\n", lines) + "\n").getBytes(StandardCharsets.UTF_8));
        lines.forEach(System.out::println);
        System.exit(deviations > 0 ? 1 : 0);
    }

    // --- reading the reference data -----------------------------------------

    static Case parse(String line) {
        String[] f = line.split(";", -1);
        LocalDate day = LocalDate.parse(f[2]);
        List<Reading> readings = new ArrayList<>();
        for (String part : f[11].split("\\|")) {
            String[] p = part.split(",", -1);
            LocalDateTime at = p[0].contains("T")
                    ? LocalDateTime.parse(p[0])
                    : day.atTime(Integer.parseInt(p[0].substring(0, 2)),
                                 Integer.parseInt(p[0].substring(3, 5)));
            Double t = p[1].isBlank() ? null : Double.valueOf(p[1]);
            readings.add(new Reading(at, t, Flag.valueOf(p[2])));
        }
        // The expected outcome as one string: the same shape the implementation is asked
        // to produce, so a comparison needs no field-by-field code and misses no field.
        String expected = f[3].isBlank()
                ? String.join(" · ", "station=" + f[1], "retained=" + f[4],
                        "rejected=" + f[5], "mean=" + f[6], "min=" + f[7], "max=" + f[8],
                        "label=" + f[9], "frost=" + (f[10].isBlank() ? "none" : f[10]))
                : null;
        return new Case(f[0], new Request(f[1], day, readings), f[3].trim(), expected);
    }

    /** The outcome of one run, rendered exactly as the reference data renders it. */
    static String render(Result r) {
        StringBuilder frost = new StringBuilder();
        for (FrostEpisode e : r.frostEpisodes()) {
            if (frost.length() > 0) frost.append("+");
            frost.append(e.startedAt().format(HHMM)).append(">")
                 .append(e.endedAt().format(HHMM)).append(":").append(e.readingCount());
        }
        return String.join(" · ",
                "station=" + r.stationId(),
                "retained=" + r.retainedCount(),
                "rejected=" + r.rejectedCount(),
                "mean=" + r.meanTemperature().toPlainString(),
                "min=" + oneDecimal(r.minTemperature()),
                "max=" + oneDecimal(r.maxTemperature()),
                "label=" + r.qualityLabel(),
                "frost=" + (frost.length() == 0 ? "none" : frost));
    }

    /** A published reading, as measured: one decimal, no exponent, no float noise. */
    static String oneDecimal(double v) {
        return BigDecimal.valueOf(v).setScale(1, RoundingMode.HALF_EVEN).toPlainString();
    }

    /** The outcome of a run, or the business code that refused it. */
    static String outcome(Request request, Parameters p) {
        try {
            return render(WeatherSummary.summarise(request, p));
        } catch (BusinessError e) {
            return e.code;
        }
    }

    // --- replaying ----------------------------------------------------------

    @ImplementsSpec({"RG-005", "RG-010", "RG-020", "RG-030", "RG-040", "RG-050", "RG-060",
                     "E-WTH-001", "E-WTH-002", "E-WTH-003"})
    static void replay(Case c) {
        if (!c.expectedError().isEmpty()) {
            try {
                WeatherSummary.summarise(c.request());
                fail(c.id(), "no error raised, " + c.expectedError() + " expected");
            } catch (BusinessError e) {
                if (e.code.equals(c.expectedError())) {
                    exercised.add(c.expectedError());
                    pass(c.id(), "rejected as expected — `" + c.expectedError() + "`");
                } else {
                    fail(c.id(), "raised " + e.code + ", expected " + c.expectedError());
                }
            }
            return;
        }

        Result r;
        try {
            r = WeatherSummary.summarise(c.request());
        } catch (BusinessError e) {
            fail(c.id(), "unexpected rejection: " + e.getMessage());
            return;
        }

        String got = render(r);
        if (!got.equals(c.expected())) {
            fail(c.id(), "expected `" + c.expected() + "`, got `" + got + "`");
            return;
        }
        exercised.addAll(List.of("RG-005", "RG-010", "RG-020", "RG-030", "RG-040",
                                 "RG-050", "RG-060"));
        if (!invariants(c, r)) return;

        pass(c.id(), r.retainedCount() + " retained, " + r.rejectedCount()
                + " rejected · mean " + r.meanTemperature() + " °C · "
                + r.frostEpisodes().size() + " frost episode(s) · `" + r.qualityLabel() + "`");
    }

    /** INV-01, INV-02, INV-03 and INV-05, checked on every nominal case. */
    @ImplementsSpec({"INV-01", "INV-02", "INV-03", "INV-05"})
    static boolean invariants(Case c, Result r) {
        int usable = 0;
        for (Reading x : c.request().readings())
            if (x.temperature() != null && x.qualityFlag() == Flag.VALID
                    && x.temperature() >= -90.0 && x.temperature() <= 60.0) usable++;

        if (r.retainedCount() + r.rejectedCount() != usable)
            return violation(c, "INV-01", r.retainedCount() + " + " + r.rejectedCount()
                    + " ≠ " + usable + " usable");

        BigDecimal mean = r.meanTemperature();
        BigDecimal tolerance = BigDecimal.ONE.movePointLeft(WeatherSummary.APPROVED.p05Decimals());
        if (mean.compareTo(BigDecimal.valueOf(r.minTemperature()).subtract(tolerance)) < 0
         || mean.compareTo(BigDecimal.valueOf(r.maxTemperature()).add(tolerance)) > 0)
            return violation(c, "INV-02", "mean " + mean + " outside ["
                    + r.minTemperature() + ", " + r.maxTemperature() + "]");

        LocalDateTime previousEnd = null;
        for (FrostEpisode e : r.frostEpisodes()) {
            if (e.startedAt().isAfter(e.endedAt()))
                return violation(c, "INV-03", "episode starts after it ends");
            if (previousEnd != null && !e.startedAt().isAfter(previousEnd))
                return violation(c, "INV-03", "episodes overlap or are out of order");
            previousEnd = e.endedAt();
        }

        if (r.retainedCount() < WeatherSummary.APPROVED.p03MinReadings())
            return violation(c, "INV-05", r.retainedCount() + " retained, below P-03");

        exercised.addAll(List.of("INV-01", "INV-02", "INV-03", "INV-05"));
        return true;
    }

    static boolean violation(Case c, String invariant, String detail) {
        fail(c.id(), invariant + " violated: " + detail);
        return false;
    }

    /**
     * INV-04 — invariance under permutation, on GENERATED orders.
     *
     * Two stations send their readings in different orders. A summary that depended on it
     * would not be replayable, which is exactly what EX-03 forbids for thirty years.
     */
    @ImplementsSpec("INV-04")
    static void permutationInvariance(List<Case> cases) {
        Random rng = new Random(20260822L);   // fixed seed: the property is replayable
        int shuffles = 100, total = 0;
        for (Case c : cases) {
            if (!c.expectedError().isEmpty()) continue;
            String reference = outcome(c.request(), WeatherSummary.APPROVED);
            for (int i = 0; i < shuffles; i++) {
                List<Reading> shuffled = new ArrayList<>(c.request().readings());
                Collections.shuffle(shuffled, rng);
                String got = outcome(new Request(c.request().stationId(),
                        c.request().observationDate(), shuffled), WeatherSummary.APPROVED);
                if (!got.equals(reference)) {
                    say("");
                    say("**INV-04 violated** on " + c.id() + ": a reordering gives `"
                            + got + "` instead of `" + reference + "`");
                    deviations++;
                    return;
                }
                total++;
            }
        }
        say("## Property tested on generated inputs");
        say("");
        say("| Property | Inputs | Result |");
        say("|---|---|---|");
        say("| `INV-04` — the result is invariant under permutation of the readings | "
                + total + " reorderings | OK |");
        exercised.add("INV-04");
    }

    /**
     * Which cases actually DECIDE each parameter.
     *
     * A parameter that appears in the code is not a parameter under test. It is under test
     * only if some case would publish something different were it changed — so each case
     * is re-run with one parameter perturbed, and the parameter counts as verified only if
     * at least one outcome moves.
     */
    @ImplementsSpec({"P-01", "P-02", "P-03", "P-04", "P-05", "P-06"})
    static void parameterArbitration(List<Case> cases) {
        for (Perturbation p : PERTURBATIONS) {
            List<String> movers = new ArrayList<>();
            for (Case c : cases) {
                String approved = outcome(c.request(), WeatherSummary.APPROVED);
                if (!outcome(c.request(), p.value()).equals(approved)) movers.add(c.id());
            }
            decidedBy.put(p.id(), movers);
            if (!movers.isEmpty()) exercised.add(p.id());
        }
        say("");
        say("## Parameters, and which cases decide them");
        say("");
        say("*Each case is replayed with one parameter changed. A case \"decides\" a");
        say("parameter when that change moves its published outcome — with the perturbation");
        say("shown, and no other.*");
        say("");
        say("| Parameter | Perturbation applied | Decided by |");
        say("|---|---|---|");
        for (Perturbation p : PERTURBATIONS) {
            List<String> movers = decidedBy.get(p.id());
            say("| `" + p.id() + "` | " + p.description() + " | "
                    + (movers.isEmpty() ? "**no case — its value is never arbitrated**"
                                        : String.join(", ", movers)) + " |");
        }
    }

    // --- coverage of the specification --------------------------------------

    static void coverageReport(Path spec) throws IOException {
        String text = Files.readString(spec);
        // The identities annexe cites every object: reading it would take a UUID for the
        // statement of an invariant. We stop at the body of the document.
        int annexe = text.indexOf(ANNEXE_TITRE);
        if (annexe >= 0) text = text.substring(0, annexe);

        Map<String, String> required = new LinkedHashMap<>();
        collect(required, text, "^###\\s+(RG-\\d+)\\s+—\\s+(.+)$");
        collect(required, text, ANCRE + "`(INV-\\d+)`\\s*\\|\\s*([^|]+)");
        collect(required, text, ANCRE + "`(E-[A-Z]+-\\d+)`\\s*\\|\\s*([^|]+)");
        collect(required, text, ANCRE + "`(P-\\d+)`\\s*\\|\\s*([^|]+)");

        say("");
        say("## Coverage of what the specification requires");
        say("");
        say("| Item | Statement | Covered |");
        say("|---|---|---|");
        int uncovered = 0;
        for (var e : required.entrySet()) {
            boolean ok = exercised.contains(e.getKey());
            if (!ok) uncovered++;
            say("| `" + e.getKey() + "` | " + truncate(e.getValue(), 56) + " | "
                    + (ok ? "yes" : "**NO**") + " |");
        }
        if (uncovered > 0) {
            deviations += uncovered;
            say("");
            say("**" + uncovered + " item(s) of the specification are exercised by no test.**");
        }
    }

    static void collect(Map<String, String> into, String text, String regex) {
        Matcher m = Pattern.compile(regex, Pattern.MULTILINE).matcher(text);
        while (m.find()) into.putIfAbsent(m.group(1), m.group(2).trim());
    }

    static String truncate(String s, int n) {
        s = s.replaceAll("\\s+", " ").replace("|", "/").trim();
        return s.length() > n ? s.substring(0, n) + "…" : s;
    }

    static void say(String s) { lines.add(s); }

    static void pass(String id, String detail) {
        say("| `" + id + "` | OK | " + detail + " |");
    }

    static void fail(String id, String detail) {
        say("| `" + id + "` | **DEVIATION** | " + detail + " |");
        deviations++;
    }
}
