// Qualification of the implementation against the reference data, WITH a coverage report.
//
// The harness holds no expected value of its own: it replays reference-data.csv, which is
// section 10 of the specification. And it reads the specification itself to answer the
// question a passing test suite never answers on its own:
//
//     does what we ran actually cover what the specification requires?
//
//     javac -d /tmp/as *.java && java -cp /tmp/as AverageSpeedTest
//
// Exit code: 1 if a case deviates or a required item is uncovered, 0 otherwise.

package method.averagespeed;

import method.spec.ImplementsSpec;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.MathContext;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.regex.*;

public final class AverageSpeedTest {

    /** Début d'une ligne de tableau, avec l'ancre explicite que porte la spécification. */
    static final String ANCRE = "^\\|\\s*(?:<a id=\"[^\"]+\"></a>)?\\s*";

    static final List<String> lines = new ArrayList<>();
    static final Set<String> exercised = new TreeSet<>();   // rules, invariants, errors
    static int deviations = 0;

    public static void main(String[] args) throws IOException {
        System.setOut(new java.io.PrintStream(new java.io.FileOutputStream(
                java.io.FileDescriptor.out), true, StandardCharsets.UTF_8));

        Path data = Paths.get(args.length > 0 ? args[0] : "reference-data.csv");
        Path spec = Paths.get(args.length > 1 ? args[1] : "../2-SPEC-SPD-001.en.md");

        say("# Test report — SPEC-SPD-001");
        say("");
        say("*Generated by `AverageSpeedTest`. Expected values come from the specification,");
        say("never from the implementation.*");
        say("");
        say("## Reference cases");
        say("");
        say("| Case | Result | Detail |");
        say("|---|---|---|");

        for (String line : Files.readAllLines(data, StandardCharsets.UTF_8))
            if (!line.isBlank() && !line.startsWith("#")) replay(line);

        say("");
        checkInvariantOnGeneratedJourneys();
        coverageReport(spec);

        String verdict = deviations == 0
                ? "**All reference cases pass, and every required item is covered.**"
                : "**" + deviations + " item(s) in deviation.**";
        say("");
        say(verdict);

        Path report = Paths.get(args.length > 2 ? args[2] : "reports/TEST-REPORT.md");
        Files.createDirectories(report.toAbsolutePath().getParent());
        Files.write(report, String.join("\n", lines).getBytes(StandardCharsets.UTF_8));
        lines.forEach(System.out::println);
        System.exit(deviations > 0 ? 1 : 0);
    }

    /** Replays one reference case and compares it with the expected value. */
    @ImplementsSpec({"RG-010", "RG-020", "RG-030", "E-SPD-001"})
    static void replay(String line) {
        String[] f = line.split(";", -1);
        String id = f[0], expectedError = f[1].trim(), expectedSpeed = f[2].trim();

        List<AverageSpeed.Leg> legs = new ArrayList<>();
        for (String part : f[3].split("\\|")) {
            String[] p = part.split(":");
            legs.add(new AverageSpeed.Leg(new BigDecimal(p[0]), new BigDecimal(p[1])));
        }

        if (!expectedError.isEmpty()) {
            try {
                AverageSpeed.compute(legs);
                fail(id, "no error raised, " + expectedError + " expected");
            } catch (AverageSpeed.BusinessError e) {
                if (e.code.equals(expectedError)) {
                    exercised.add(expectedError);
                    pass(id, "rejected as expected — `" + expectedError + "`");
                } else {
                    fail(id, "raised " + e.code + ", expected " + expectedError);
                }
            }
            return;
        }

        AverageSpeed.Result r;
        try {
            r = AverageSpeed.compute(legs);
        } catch (AverageSpeed.BusinessError e) {
            fail(id, "unexpected rejection: " + e.getMessage());
            return;
        }

        BigDecimal expected = new BigDecimal(expectedSpeed);
        if (r.averageSpeed().compareTo(expected) != 0) {
            fail(id, "expected " + expected + " km/h, got " + r.averageSpeed());
            return;
        }
        exercised.addAll(List.of("RG-010", "RG-020", "RG-030"));

        // INV-01 and INV-02 are checked on every nominal case, not only when asked.
        if (!invariant01(legs, r.averageSpeed())) {
            fail(id, "INV-01 violated: " + r.averageSpeed() + " km/h is outside the leg speeds");
            return;
        }
        if (!invariant02(r)) {
            fail(id, "INV-02 violated: average × duration ≠ total distance");
            return;
        }
        exercised.addAll(List.of("INV-01", "INV-02"));

        // The arithmetic mean of the speeds is the mistake this specification prevents.
        BigDecimal naive = BigDecimal.ZERO;
        for (AverageSpeed.Leg l : legs) naive = naive.add(l.speed());
        naive = naive.divide(BigDecimal.valueOf(legs.size()), 1, AverageSpeed.P_01_ROUNDING_MODE);
        String note = naive.compareTo(expected) == 0
                ? "**does not discriminate** — the naive mean gives the same answer"
                : "discriminates: the naive mean would give " + naive + " km/h";
        pass(id, r.averageSpeed() + " km/h · " + note);
    }

    /** INV-01 — the average lies between the slowest and the fastest leg. */
    @ImplementsSpec("INV-01")
    static boolean invariant01(List<AverageSpeed.Leg> legs, BigDecimal average) {
        BigDecimal min = legs.get(0).speed(), max = legs.get(0).speed();
        for (AverageSpeed.Leg l : legs) {
            min = min.min(l.speed());
            max = max.max(l.speed());
        }
        return average.compareTo(min) >= 0 && average.compareTo(max) <= 0;
    }

    /** INV-02 — before rounding, average × duration = total distance. */
    @ImplementsSpec("INV-02")
    static boolean invariant02(AverageSpeed.Result r) {
        MathContext mc = new MathContext(20);
        BigDecimal unrounded = r.totalDistance().divide(r.totalDuration(), mc);
        BigDecimal rebuilt = unrounded.multiply(r.totalDuration(), mc);
        BigDecimal gap = rebuilt.subtract(r.totalDistance()).abs();
        return gap.compareTo(r.totalDistance().multiply(new BigDecimal("1E-15"))) <= 0;
    }

    /**
     * INV-01 on GENERATED journeys. Four hand-written cases cannot establish a property
     * that must hold for every input — and this is the property that catches the very
     * mistake the specification exists to prevent.
     */
    static void checkInvariantOnGeneratedJourneys() {
        Random rng = new Random(20260822L);   // fixed seed: the run is replayable
        int journeys = 500;
        for (int i = 0; i < journeys; i++) {
            List<AverageSpeed.Leg> legs = new ArrayList<>();
            for (int n = 1 + rng.nextInt(8); n > 0; n--)
                legs.add(new AverageSpeed.Leg(
                        BigDecimal.valueOf(1 + rng.nextInt(500)),
                        BigDecimal.valueOf(1 + rng.nextInt(200))));
            AverageSpeed.Result r = AverageSpeed.compute(legs);
            if (!invariant01(legs, r.averageSpeed())) {
                say("");
                say("**INV-01 violated on a generated journey:** " + legs);
                deviations++;
                return;
            }
        }
        say("## Property tested on generated inputs");
        say("");
        say("| Property | Journeys | Result |");
        say("|---|---|---|");
        say("| `INV-01` — the average lies between the slowest and the fastest leg | "
                + journeys + " | OK |");
        exercised.add("INV-01");
    }

    /**
     * Reads the specification and reports what the run did NOT cover. A green suite proves
     * nothing about the cases nobody wrote.
     */
    static void coverageReport(Path spec) throws IOException {
        String text = Files.readString(spec);
        // L'annexe des identités cite tous les objets : la lire ferait passer un UUID
        // pour l'énoncé d'un invariant. On s'arrête au corps du document.
        int annexe = text.indexOf("## Annexe — Identités");
        if (annexe >= 0) text = text.substring(0, annexe);
        Map<String, String> required = new LinkedHashMap<>();
        collect(required, text, "^###\\s+(RG-\\d+)\\s+—\\s+(.+)$", Pattern.MULTILINE);
        collect(required, text, ANCRE + "`(INV-\\d+)`\\s*\\|\\s*([^|]+)", Pattern.MULTILINE);
        collect(required, text, ANCRE + "`(E-[A-Z]+-\\d+)`\\s*\\|\\s*([^|]+)", Pattern.MULTILINE);

        say("");
        say("## Coverage of what the specification requires");
        say("");
        say("| Item | Statement | Covered |");
        say("|---|---|---|");
        int uncovered = 0;
        for (var e : required.entrySet()) {
            boolean ok = exercised.contains(e.getKey());
            if (!ok) uncovered++;
            say("| `" + e.getKey() + "` | " + truncate(e.getValue(), 60) + " | "
                    + (ok ? "yes" : "**NO**") + " |");
        }
        if (uncovered > 0) {
            deviations += uncovered;
            say("");
            say("**" + uncovered + " item(s) of the specification are exercised by no test.**");
        }
    }

    static void collect(Map<String, String> into, String text, String regex, int flags) {
        Matcher m = Pattern.compile(regex, flags).matcher(text);
        while (m.find()) into.putIfAbsent(m.group(1), m.group(2).trim());
    }

    static String truncate(String s, int n) {
        s = s.replaceAll("\\s+", " ").replace("|", "/");
        return s.length() > n ? s.substring(0, n) + "…" : s;
    }

    static void say(String s) { lines.add(s); }

    static void pass(String id, String detail) {
        say("| `" + id + "` | OK | " + detail + " |");
    }

    static void fail(String id, String detail) {
        say("| `" + id + "` | **DEVIATION** | " + detail + " |");
        deviations++;
    }
}
